### ISSUE TITLE
Error: No WebRTC support: Specify `opts.wrtc` option in this environment

### ISSUE THREAD

**Issue by chovy** [feross/simple-peer#110]
Not sure why but I got this error once in awhile.

        Error: No WebRTC support: Specify `opts.wrtc` option in this environment
            at new Peer (/home/username/tmp/spider/node_modules/simple-peer/index.js:61:13)
            at generateOffer (/home/username/tmp/spider/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:374:38)
            at WebSocketTracker._generateOffers (/home/username/tmp/spider/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:367:5)
            at WebSocketTracker.announce (/home/username/tmp/spider/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:66:10)
            at WebSocketTracker._onSocketConnect (/home/username/tmp/spider/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:187:10)
            at Socket.self._onSocketConnectBound (/home/username/tmp/spider/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:154:10)
            at Socket.g (events.js:291:16)
            at emitNone (events.js:91:20)
            at Socket.emit (events.js:185:7)
            at Socket._onOpen (/home/username/tmp/spider/node_modules/simple-websocket/index.js:223:8)

**Comment by feross** [comment]
This issue should probably have been posted to the WebTorrent issue tracker.

How are you using `webtorrent`? Are you using it in the browser? Or using the module in Node.js with `require()`? Or the CLI tool?

**Comment by chovy** [comment]
In node.js

**Comment by feross** [comment]
Can you paste your code here? How are you initializing the `WebTorrent` constructor?

**Comment by feross** [comment]
So here's what I think is happening: somehow `webrtcSupport` is getting set to `true` for you on [this line](https://github.com/feross/bittorrent-tracker/blob/a727fd9012536fc870e68a4256bab2382fd4f6e7/client.js#L100) in `bittorrent-tracker`. That means that even though you're running in Node.js without WebRTC support, a `WebSocketTracker` is getting created for your torrent. When the websocket connection to the tracker is opened, then you try to create RTCPeerConnection (webrtc) objects, which don't exist in Node.js of course.

The only way the error you're getting could possibly happen (as far as I can tell), is if you're setting the `wrtc` option in `WebTorrent` like this:

```js
new WebTorrent({ tracker: { wrtc: true }})
```

Or you're setting `global.WRTC` to a truthy value, or using a shim for `RTCPeerConnection` that is confusing the `get-browser-rtc` module's detection code.

If you have any new info, please share.
