### ISSUE TITLE
getStats cb is not a function

### ISSUE THREAD

**Issue by SourceBoy** [feross/simple-peer#119]
When using electron-webrtc@v0.2.12 in Node 6 with simple-peer@v6.1.3:

```
node_modules/electron-webrtc/src/RTCPeerConnection.js:260
        cb({ result: () => res })
        ^

TypeError: cb is not a function
    at _callRemote (node_modules/electron-webrtc/src/RTCPeerConnection.js:260:9)
    at Daemon.daemon.once (node_modules/electron-webrtc/src/RTCPeerConnection.js:277:11)
    at Daemon.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Daemon.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:217:18)
```

Rolling back to v6.1.0 works fine (have not tried 6.1.1 nor 6.1.2)

**Comment by feross** [comment]
The latest version of `simple-peer` breaks `electron-webrtc` because the way that we detect `getStats` has changed slightly.

Before `simple-peer`@6.1.2, `electron-webrtc` was getting the Chrome code path, which calls `getStats(cb)`. Now it's getting detected as an "other" browser, so it gets called the spec-compliant callback way: `getStats(null, cb)`.

I just fixed it in a PR by detecting `electron-webrtc`. Eventually, everyone will be on spec-compliant promise API and we can remove this error-prone detection code.

Cheers!
