### ISSUE TITLE
TypeError: Cannot read property 'bufferedAmountLowThreshold' of null

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#165]
```js
TypeError: Cannot read property 'bufferedAmountLowThreshold' of null
    at /home/travis/build/feross/simple-peer/index.js:607:29
    at /home/travis/build/feross/simple-peer/index.js:493:7
    at _callRemote (/home/travis/build/feross/simple-peer/node_modules/electron-webrtc/src/RTCPeerConnection.js:260:9)
    at Daemon.daemon.once (/home/travis/build/feross/simple-peer/node_modules/electron-webrtc/src/RTCPeerConnection.js:277:11)
    at Daemon.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Daemon.emit (events.js:188:7)
    at ChildProcess.<anonymous> (/home/travis/build/feross/simple-peer/node_modules/electron-eval/lib/index.js:195:27)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
```

From a recent test run: https://travis-ci.org/feross/simple-peer/builds/219835468

**Comment by feross** [comment]
Looks like we need another `self.destroyed` guard for `wrtc`. I'll add it

**Comment by feross** [comment]
Actually, I can even this sometimes in Chrome during the test suite. I think it's pretty easy to hit this if you call `destroy()` before the ready event. Then `getStats()` gets called and tries to refer to `self._channel` which has already been nulled.

**Comment by feross** [comment]
7.0.2

**Comment by RationalCoding** [comment]
Opened and issue in wrtc too, since this behaviour isn't spec compliant. Hopefully someone will fix it. [314](https://github.com/js-platform/node-webrtc/issues/314)

**Comment by feross** [comment]
@RationalCoding thanks!
