### ISSUE TITLE
 Uncaught Error: Secure random number generation is not supported by this browser

### ISSUE THREAD

**Issue by jcollognat** [feross/simple-peer#745]
Hello,

I really want to use this library but I receive the error below in the JS console when I try to make the first example working :
`Uncaught Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11`

Tested on Firefox and Chrome, they are up to date of course. 
I tried to use the `simplepeer.min.js` standalone script directly in a <script> tag as well as the browserify method.

Thanks for your help.

**Comment by feross** [comment]
Can you share the full stack trace of the error message?

**Comment by jcollognat** [comment]
Hello,

Here's the full stack : 
` Uncaught Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    oldBrowser https://webconf.myconf.com/js/class/webconf/init.bundle.js:813
    Peer https://webconf.myconf.com/js/class/webconf/init.bundle.js:4076
    [29]< https://webconf.myconf.com/js/class/webconf/init.bundle.js:5774
    o https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
    r https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
    <anonymous> https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
init.bundle.js:813:9
    oldBrowser https://webconf.myconf.com/js/class/webconf/init.bundle.js:813
    Peer https://webconf.myconf.com/js/class/webconf/init.bundle.js:4076
    [29]< https://webconf.myconf.com/js/class/webconf/init.bundle.js:5774
    o https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
    r https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
    <anonyme> https://webconf.myconf.com/js/class/webconf/init.bundle.js:1
​`
Line 813 - function oldBrowser : 
`  throw new Error('Secure random number generation is not supported by this browser.\nUse Chrome, Firefox or Internet Explorer 11')
`

Line 4076 - Peer constructor : 
`    this._id = randombytes(4).toString('hex').slice(0, 7)
`

Line 5774 : Peer Object instantiation :
`const p = new SimplePeer({
`

And finally the code of my browserify bundle :
`const SocketIOFileClient = require('socket.io-file-client');
const SimplePeer = require('simple-peer');

const p = new SimplePeer({
	initiator: location.hash === '#1',
	trickle: false
})

p.on('error', err => console.log('error', err))

p.on('signal', data => {
	console.log('SIGNAL', JSON.stringify(data))
	document.querySelector('#outgoing').textContent = JSON.stringify(data)
})

document.querySelector('form').addEventListener('submit', ev => {
	ev.preventDefault()
	p.signal(JSON.parse(document.querySelector('#incoming').value))
})

p.on('connect', () => {
	console.log('CONNECT')
	p.send('whatever' + Math.random())
})

p.on('data', data => {
	console.log('data: ' + data)
})

window.addEventListener('load', function () {
	WebRTC.init();
	WebSocket.connect(SocketIOFileClient);
	Chat.init();
	DocumentSharing.init();
	ScreenSharing.init();

	if (isOrganizer) {
		ConferenceSessionMonitoring.init($('#participants_list'), conferenceRoom, true);
		new CountDown($('.count_down'), (completeCallback) => ConferenceSessionMonitoring.doRequestAndRefresh(completeCallback));
	}
}, false);`

**Comment by feross** [comment]
Can you open your webpage and run this in the console:

```js
window.crypto.getRandomValues
```

What do you get?

**Comment by jcollognat** [comment]
`
getRandomValues()
​
length: 1
​
name: "getRandomValues"

`

**Comment by feross** [comment]
Not sure what this could be. Maybe you've modified the `getRandomValues` function somehow? If you figure this out, send a PR.

**Comment by feross** [comment]
Are you by chance using `react-native`? I've seen this error happen in that environment: See: https://github.com/webtorrent/webtorrent/issues/1740#issuecomment-530149608

**Comment by jcollognat** [comment]
No I'm using `Symfony`... I gave up the idea of ​​using this library, I'm using the native WebRTC API.

Thanks for the help !

**Comment by hbirler** [comment]
Hi, I had this issue with SvelteKit/Vite as my environment and I solved it by installing the @rollup/plugin-inject plugin. Otherwise the randombytes package does not find `crypto`.

**Comment by GagnDeep** [comment]
@hbirler what you injected with @rollup/plugin-inject? I am also having same issues while using svelte and vite

**Comment by hbirler** [comment]
Hi @GagnDeep , I actually don't remember what exactly I had done. I could fix the error with `crypto` but then I believe I got other errors from other node builtins that I did not manage to polyfill properly. In the end I gave up on using `simple-peer` and implemented something based on https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation. I did not even save my experiments with `simple-peer`; I don't have the code anymore. I am not that experienced with node and its ecosystem so rewriting stuff felt less frustrating than fixing packaging errors :upside_down_face:

**Comment by RamanSB** [comment]
I have this error, I'm using react-native with expo-go, I've created a custom development build with `react-native-get-random-values`, `crypto`, `react-native-webcrypto` `rn-nodeify`, `events`, `simple-peer`... Still getting this error
 

WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at oldBrowser (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:193688:20)
    at Peer (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:192672:30)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:187408:43)
    at apply (native)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:203012:27)
    at onconnect (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:204795:26)
    at onpacket (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:204678:29)
    at apply (native)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:203012:27)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:203969:30)
    at tryCallOne (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39710:26)
    at _callTimer (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39589:17)
    at _callReactNativeMicrotasksPass (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39634:17)
    at callReactNativeMicrotasks (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39840:44)
    at __callReactNativeMicrotasks (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3643:46)
    at anonymous (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3417:45)
    at __guard (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3616:15)
    at flushedQueue (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3416:21)
    at callFunctionReturnFlushedQueue (http://192.168.0.19:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3401:33)

**Comment by RC0D3** [comment]
After a lot of try I can solve.
https://stackoverflow.com/questions/75714004/is-there-a-browserify-for-vite-how-can-i-use-webrtc-swarm-with-a-vite-based-pro/75714700#75714700


3° way option work as well.

**Comment by hxk1633** [comment]
I'm having the same exact error that everyone is describing here. Can someone please provide a workaround or fix for this please?

**Comment by jbflow** [comment]
Also seeing this error, SO answer posted by @RC0D3 doesn't seem to be working in my case. I'm using Vite and React. simple-peer worked fine in react before when I was using webpack.

**Comment by GagnDeep** [comment]
@jbflow You can try to see if global is defined and its referencing `window` object. Try adding `<script> window.global = window </script>` in your index.html file before every script tag to test. When i was facing this issue global was defined but it was an empty object, but making sure that global is referencing window solved this issue.

**Comment by yolo-pranav** [comment]
This is happening because "randombytes" is not updated to the latest version.
Adding the line ```"module": "browser.js",``` to ```package.json``` under ```node_modules/randombytes``` will make it working.

Kindly remove this dependency and generate randombytes directly to solve the issue.

**Comment by maxclaus** [comment]
Meanwhile randombytes fixing isn't published, this workaround based on npm "overrides" pointing to the fixing commit seems to have worked for me for me:
```
  "overrides": {
    "simple-peer": {
      "randombytes": "browserify/randombytes#b4eb412"
    }
  }
```
For full context, to get this lib to work on Vite project, I also needed this vite configuration:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { nodePolyfills } from "vite-plugin-node-polyfills";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    nodePolyfills({
      include: [
        "buffer",
      ],
    }),
  ],
  define: {
    global: {},
  },
});

```
