### ISSUE TITLE
Re Connected event

### ISSUE THREAD

**Issue by hatimtekri** [feross/simple-peer#841]
Error connection failed event occuring perfectly but in some case their is no disturbance in communication i mean user have not realized any disturbance due to this error 
So that's mean it have reconnect very quickly 
So what is the even t for capturing re connect logs 
Please help

**Comment by Mihai-github** [comment]
Hi, having the same issue.

`Error: Connection failed.
    at makeError (index.js:17:1)
    at Peer._onConnectionStateChange (index.js:654:1)
    at RTCPeerConnection.Peer._pc.onconnectionstatechange (index.js:119:1)
`

Sometimes, if I disconnect and destroy the connection before leaving and then reconnect or try to create a new connection, I get the above error.

Someone whos better at this maybe know the issue?. My guess is because one peer emits a new offer/answer but the second peer does not do this and they can be connected after the session got destroyed?
