### ISSUE TITLE
global is not defined (SvelteKit/Vite)

### ISSUE THREAD

**Issue by pjebs** [feross/simple-peer#883]
```
global is not defined
ReferenceError: global is not defined
    at node_modules/randombytes/browser.js (http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:2351:18)
    at __require (http://localhost:3000/node_modules/.vite/chunk-UNANNA3Z.js?v=10be15c3:38:50)
    at node_modules/simple-peer/index.js (http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:5160:23)
    at __require (http://localhost:3000/node_modules/.vite/chunk-UNANNA3Z.js?v=10be15c3:38:50)
    at http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:6017:27
```

```
    <script>
    	import { SimplePeer} from "simple-peer"
import { browser } from '$app/env';
	
	if (browser) {


 const p = new SimplePeer({
        initiator: location.hash === '#1',
        trickle: false
      })

      p.on('error', err => console.log('error', err))

      p.on('signal', data => {
        console.log('SIGNAL', JSON.stringify(data))
        document.querySelector('#outgoing').textContent = JSON.stringify(data)
      })

      document.querySelector('form').addEventListener('submit', ev => {
        ev.preventDefault()
        p.signal(JSON.parse(document.querySelector('#incoming').value))
      })

      p.on('connect', () => {
        console.log('CONNECT')
        p.send('whatever' + Math.random())
      })

      p.on('data', data => {
        console.log('data: ' + data)
      })

	}

     
    </script>

        <style>
      #outgoing {
        width: 600px;
        word-wrap: break-word;
        white-space: normal;
      }
    </style>

    <form>
      <textarea id="incoming"></textarea>
      <button type="submit">submit</button>
    </form>
    <pre id="outgoing"></pre>
```

**Comment by pjebs** [comment]
I also tried `import * as SimplePeer from "simple-peer"`

**Comment by pjebs** [comment]
The issue seems to be in the `randombytes` library

**Comment by pjebs** [comment]
My solution was to just add the `simplepeer.min.js` file without importing and then use `window.SimplePeer`.
I couldn't find any other work-around.

**Comment by Swepool** [comment]
Got the same issue

**Comment by Swepool** [comment]
I did `var global = global || window;` in index.html

**Comment by pjebs** [comment]
@Swepool Your trick didn't work for me. It stopped the `global is not defined` error.
But then SimplePeer gave me this error.
```
TypeError: Cannot read properties of undefined (reading 'call')
    at Peer.Readable (_stream_readable.js:184:10)
    at new Duplex (_stream_duplex.js:60:12)
    at new Peer (index.js:34:5)
    at gotMedia (caller.svelte? [sm]:14:4)
```

**Comment by ErcouldnT** [comment]
Any solution for this so far?

**Comment by pjebs** [comment]
@ErcouldnT https://github.com/feross/simple-peer/issues/883#issuecomment-1094142165

**Comment by ErcouldnT** [comment]
> 

How do you get this script file?

**Comment by pjebs** [comment]
It's in the repo https://github.com/feross/simple-peer/blob/master/simplepeer.min.js

**Comment by machester4** [comment]
Fixed with

https://stackoverflow.com/questions/68975837/web3js-fails-to-import-in-vue3-composition-api-project/69021714#69021714

**Comment by wmcmurray** [comment]
This worked for me:
```js
import SimplePeer from 'simple-peer/simplepeer.min.js'
```

**Comment by Ziao** [comment]
In short, when using Vite, this is the fix until this gets properly addressed.

In your vite.config.ts, add a `resolve` section with the following content. This tells the bundler to use the pre-bundled SimplePeer code whenever you import it. As a bonus, you get to keep the types, when using Typescript.

```js
resolve: {
    alias: {
      // ...
      "simple-peer": "simple-peer/simplepeer.min.js",
    },
  },
```

**Comment by AAAAsea** [comment]
> 

It worked elegantly. Thx : )

**Comment by realrecordzLab** [comment]
> This worked for me:
> 
> ```js
> import SimplePeer from 'simple-peer/simplepeer.min.js'
> ```

I had the same problem in a vue/vite app. Solved by importing the compiled library like showed into the comment

**Comment by maxclaus** [comment]
Another workaround is overriding randombytes dependency like this https://github.com/feross/simple-peer/issues/745#issuecomment-2562657363
