### ISSUE TITLE
simple-peer.js?v=eb7dd428:571 Uncaught (in promise) Error: Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11     at oldBrowser (simple-peer.js?v=eb7dd428:571:13)     at new _Peer (simple-peer.js?v=eb7dd428:5966:20)     at prepareNewPeerConnection (webRTCHandler.js:59:29)     at Socket2.<anonymous> (socketConnection.js:58:5)     at Emitter.emit (socket__io-client.js?v=77d8b3f1:427:21)     at Socket2.emitEvent (socket__io-client.js?v=77d8b3f1:2731:16)     at Socket2.onevent (socket__io-client.js?v=77d8b3f1:2719:12)     at Socket2.onpacket (socket__io-client.js?v=77d8b3f1:2690:14)     at Emitter.emit (socket__io-client.js?v=77d8b3f1:427:21)     at socket__io-client.js?v=77d8b3f1:3287:12             i m getting this error while using react vite please can anybody solve this error i m stuck

### ISSUE THREAD

**Issue by amaann2** [feross/simple-peer#932]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by MohamedAmineNasri** [comment]
@amaann2 i'm facing the same issue

**Comment by MohamedAmineNasri** [comment]
it worked for me using this import `import Peer from 'simple-peer/simplepeer.min.js'`
instead of this  `import Peer from 'simple-peer';`
and without using **global** in defineConfig in vite 

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
```

**Comment by codewithdripzy** [comment]
found the solution to this, just in your `vite.config.ts` or `vite.cofig.js` comment out `global: {}`, worked for me, your vite.config.ts file should look like this 
```[ts]import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), nodePolyfills({
    exclude : []
  }),
],
  define: {
    // global: {}
  },
})

**Comment by garnsworthy** [comment]
import { nodePolyfills } from 'vite-plugin-node-polyfills'
import { viteCommonjs } from "@originjs/vite-plugin-commonjs";

export default defineConfig({
  plugins: [
    react(),
    nodePolyfills({include:['crypto', 'buffer', 'stream', 'util']}),
    viteCommonjs(),
  ],

I am using node-bignumber to calculate an RSA encrypt value, I have to require it instead of import it, that is the viteCommonjs.  Then I have to polyfill crypto and buffer for it, that is the polyfills.

Then commenting out global fixed the issue with randomNumber missing for me for some reason.  So thanks!

**Comment by FarhanDevelopeir** [comment]
@codewithdripzy thanks brother it's working
