### ISSUE TITLE
Vite-React-Typescript Issue - Uncaught TypeError: Stream is undefined at the time of createing SimplePeer object

### ISSUE THREAD

**Issue by Atanusaha143** [feross/simple-peer#933]

**Comment by codewithdripzy** [comment]
Also getting this error recently `simple-peer.js?t=171…965&v=ca1ffffe:4300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at _Peer.Readable (simple-peer.js?t=171…&v=ca1ffffe:4300:14)
    at new Duplex (simple-peer.js?t=171…&v=ca1ffffe:3569:16)
    at new _Peer (simple-peer.js?t=171…5&v=ca1ffffe:5309:9)
    at createPeer (Room.tsx:87:22)
    at Room.tsx:41:34
    at Array.forEach (<anonymous>)
    at Socket2.<anonymous> (Room.tsx:40:25)
    at Emitter.emit (socket__io-client.js?v=ca1ffffe:356:21)
    at Socket2.emitEvent (socket__io-client.js?v=ca1ffffe:2600:16)
    at Socket2.onevent (socket__io-client.js?v=ca1ffffe:2588:12)`

**Comment by codewithdripzy** [comment]
After checking through, i was able to find a solution that worked 
`https://stackoverflow.com/questions/76083232/caught-in-promise-typeerror-cannot-read-properties-of-undefined-reading-cal`
`https://www.npmjs.com/package/vite-plugin-node-polyfills`

**Comment by Atanusaha143** [comment]
@codewithdripzy, Your provided link is not working
